// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Phase1_Projects_Backend.Models;

namespace Phase1_Projects_Backend.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20211006065624_two migrations deleted")]
    partial class twomigrationsdeleted
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Phase1_Projects_Backend.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechTools")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("To be Updated");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 10,
                            ContactMail = "Email10",
                            Description = "Description10",
                            Domain = "Domain10",
                            ProjectTitle = "Title10",
                            TechTools = "Technologies and Tools 10"
                        },
                        new
                        {
                            ProjectId = 11,
                            ContactMail = "Email11",
                            Description = "Description11",
                            Domain = "Domain11",
                            ProjectTitle = "Title11",
                            TechTools = "Technologies and Tools 11"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
